In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data_path = '/media/hayk/STORAGE/dev/repos/Starke/AI4Animation/AI4Animation/SIGGRAPH_Asia_2019/Export/'
input = np.loadtxt(data_path + 'Input.txt', dtype = np.float16)
output = np.loadtxt(data_path + 'Output.txt', dtype = np.float16)

In [3]:
input_norm = np.loadtxt(data_path + 'InputNorm.txt')
output_norm = np.loadtxt(data_path + 'OutputNorm.txt')

In [16]:
abs(output[:,:276].mean(0) - input[:,:276].mean(0)).mean()

2.54e-05

In [8]:
sum(output_norm[1] == 0)

6

In [32]:
input_norm[0,276]

0.0

In [33]:
input[:,276]

array([-0.00573, -0.00546, -0.0052 , ...,  0.2065 ,  0.2289 ,  0.2476 ],
      dtype=float16)

In [20]:
data = np.concatenate([input, output], 1)
data.shape

(359486, 5823)

In [21]:
np.save('./data/data16.npy', data)

In [23]:
np.save('./data/input_norm.npy', input_norm)
np.save('./data/output_norm.npy', output_norm)

In [12]:
im = input.mean(0)
om = output.mean(0)

In [ ]:
output.mean(0)

In [8]:
output.shape

(359486, 618)

In [92]:
np.set_printoptions(precision=5,suppress = True)

In [2]:
data = np.load('./data/dataset16.npy')

In [22]:
mi,si = np.load('./data/input_norm.npy')
mo,so = np.load('./data/output_norm.npy')

In [25]:
sum(si == 0)

6

In [55]:
abs(si[:276] - so[:276]).argmax()

2

In [93]:
si[2],so[2]

(0.0, 0.00977)

In [94]:
abs(std_i[:276] - std_o[:276]).max()

0.00977

In [40]:
A = np.random.random(276)

In [41]:
def normalize(x,m,s):
    s[s==0] = 1
    return (x - m[:len(x)]) / s[:len(x)]

def unnormalize(x,m,s):
    return x * s[:len(x)] + m[:len(x)]

In [69]:
IN = np.loadtxt('/media/hayk/STORAGE/dev/repos/AI4Animation/AI4Animation/SIGGRAPH_Asia_2019/TensorFlow/data/InputNorm.txt')
ON = np.loadtxt('/media/hayk/STORAGE/dev/repos/AI4Animation/AI4Animation/SIGGRAPH_Asia_2019/TensorFlow/data/OutputNorm.txt')

In [76]:
IN[1,:10], ON[1,:10]

(array([0.     , 0.16598, 0.     , 0.06085, 0.25278, 0.11047, 0.07202,
        0.11184, 0.25476, 0.34292]),
 array([0.00569, 0.16599, 0.00977, 0.06258, 0.25279, 0.11042, 0.07217,
        0.11184, 0.25472, 0.34159]))

In [87]:
data[:,2],data[:,5437 + 2]

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float16),
 array([0.0002 , 0.00018, 0.00016, ..., 0.01541, 0.01459, 0.01412],
       dtype=float16))

In [85]:
data[:,5437 + 2].std()

0.00976

In [78]:
si[:10],so[:10]

(array([0.     , 0.16598, 0.     , 0.06085, 0.25278, 0.11047, 0.07202,
        0.11184, 0.25476, 0.34292]),
 array([0.00569, 0.16599, 0.00977, 0.06258, 0.25279, 0.11042, 0.07217,
        0.11184, 0.25472, 0.34159]))

In [44]:
abs(normalize(A,mi,si) - normalize(A,mo,so)).argmax()

228

In [125]:
data[:,2]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float16)

In [128]:
data[:,5437 + 2]

array([1.048, 1.048, 1.048, ..., 1.022, 1.026, 1.031], dtype=float16)

In [89]:
data[1]

array([0.   , 1.048, 0.   , ..., 0.683, 0.85 , 1.017], dtype=float16)

In [61]:
data[5437:5437+276].std(0)[2]

0.0

In [46]:
(mi[228],si[228]),(mo[228],so[228])

((0.09498, 0.00168), (0.09513, 0.00592))

In [102]:
data[10,:12],data[10,5437:5437+12], data[11,:12]

(array([ 0.     ,  1.048  ,  0.     , -0.01262,  0.1559 ,  0.988  ,
         0.01991,  0.988  , -0.1556 ,  0.00142, -0.00037,  0.00675],
       dtype=float16),
 array([-0.00001,  1.048  ,  0.00012, -0.01346,  0.1558 ,  0.988  ,
         0.02013,  0.988  , -0.1555 , -0.00036,  0.00006,  0.0073 ],
       dtype=float16),
 array([ 0.     ,  1.048  ,  0.     , -0.01265,  0.1558 ,  0.988  ,
         0.01999,  0.988  , -0.1555 , -0.00035,  0.00006,  0.0073 ],
       dtype=float16))

In [121]:
def diff(x,y): print (abs(x-y).mean())

In [122]:
diff(data[10,:276],data[11,:276])

0.000367


In [123]:
diff(data[10,5437:5437+276],data[11,:276])

0.0001141


In [124]:
diff(data[10,:276],data[10,5437:5437+276])

0.000392


In [119]:
data[10,116 + 5437], data[11,116]

(0.2642, 0.2651)